# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

# on-policy training
buffer_size: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 100

lr: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

hierarchy_type: 2

runner: "hierarchical_episode" # Runs 1 env for an episode
agent_output_type: "pi_logits"
learner: "hppo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "hmappo"
option_duration_limit: 100

t_max: 20050000